### PR TITLE
push/unshift menu items from submenu in linux/windows

### LINKED ISSUE #503: Not starting on linux
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
master
**What operating system and version?**
ubuntu 16.04
**What did you do?**
npm start
**What did you expect to happen?**
app starts
**What actually happened?**
Message windows 
```
Uncaught Exception:
TypeError: template[0].unshift is not a function
    at getAppMenuTemplate (/home/grunjol/workspaces/wt/webtorrent-desktop/main/menu.js:391:17)
    at Object.init (/home/grunjol/workspaces/wt/webtorrent-desktop/main/menu.js:27:45)
    at EventEmitter.<anonymous> (/home/grunjol/workspaces/wt/webtorrent-desktop/main/index.js:62:10)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
```

I think unshift should be applied to submenu, not template
#500

### PR DESCRIPTION
**Pull request by grunjol**
Fixes #503

### CODE REVIEW

**Comment by dcposch** [comment]
LGTM

**Comment by dcposch** [comment]
looks like this fixes a bug introduced in fdb7b39a0ba27d28e719a7ec3e894822078b6e51

**Comment by feross** [comment]
LGTM -- sorry about that.
